### ISSUE TITLE
Unable to use version 0.3.0 because of checksum issue.

### ISSUE THREAD

**Issue by aesterline** [protoflex/parse-ez#1]
When I added `0.3.0` as a dependency to my `project.clj`, I got the following error.

```
Could not find artifact parse-ez:parse-ez:pom:0.3.0 in central (http://repo1.maven.org/maven2)
Retrieving parse-ez/parse-ez/0.3.0/parse-ez-0.3.0.pom (2k)
    from https://clojars.org/repo/
Checksum validation failed, expected 31a9e8d4b4f390610d34ae69c0ba9bf041555115 but is 488ebd3c64179044a4832b37c551a59d20c17c73
Retrieving parse-ez/parse-ez/0.3.0/parse-ez-0.3.0.pom (2k)
    from https://clojars.org/repo/
Could not transfer artifact parse-ez:parse-ez:pom:0.3.0 from/to clojars (https://clojars.org/repo/): Checksum validation failed, expected 31a9e8d4b4f390610d34ae69c0ba9bf041555115 but is 488ebd3c64179044a4832b37c551a59d20c17c73
```

Any ideas?

**Comment by protoflex** [comment]
Hi Adam,

Sorry for the problem.  I originally pushed an unsigned version of parse-ez 0.3.0 to clojars.org.  Following clojars repository announcement post on clojure group (https://groups.google.com/forum/?fromgroups=#!topic/clojure/AsPs9ZonRPQ), I tried to push a signed version which failed.

I have now successfully pushed signed version of 0.3.1 to clojars.org.  So please change the version to 0.3.1 in your project.clj.

**Comment by aesterline** [comment]
That worked. Thank you.
