### ISSUE TITLE
Using parse from the repl switches namespace to protoflex.parse

### ISSUE THREAD

**Issue by aesterline** [protoflex/parse-ez#2]
Whenever I call parse in the repl, the namespace switches to `protoflex.parse`. Is this expected? Should I be calling another function?

**Comment by protoflex** [comment]
This is a bug in 0.3.1; will fix it.

**Comment by protoflex** [comment]
fixed in 0.3.2.

**Comment by aesterline** [comment]
Thank you. It worked.
